### ISSUE TITLE
Soil Moisture store requires five parameters

### ISSUE THREAD

**Issue by gunbra32** [dcs4cop/xcube-cds#16]
Different to the stroe description, the request requires five paramters. 
'time_period' s required, although a re-sampling is not performed. 

![grafik](https://user-images.githubusercontent.com/7138923/96860247-d18d9700-1462-11eb-90f3-3e589568820e.png)

**Comment by pont-us** [comment]
Bug confirmed in master branch. Aggregation period is already encoded into the data ID, so shouldn't need to be specified as an open parameter.
